from __future__ import annotations

HARMLESS_BROKERED_DESCRIPTIONS = (
    "Read basic telemetry",
    "Count model tokens",
    "Count model tokens 100",
    "Count model tokens: 1,000.",
    "Count input tokens\U00010d50",
)

UNSAFE_BROKERED_DESCRIPTIONS = (
    "contains sk-secret",
    "execution at https://tool.default",
    "Bearer token required",
    "Basic Zm9vOmJhcg==",
    "Basİc dXNlcjpwYXNz",
    "Basic=dXNlcjpwYXNz",
    "Basic user:pass",
    "Basic alice: pass1",
    "basic mode. baſic-@dXNlcjpwYXNz",
    "BASIC baſic=Basic[baſic]Zm9vOmJhcg==",
    "alice:pass is the Basic credential",
    "Use Basic credential abc123",
    "Use Basic `dXNlcjpwYXNz`",
    "Use HTTP Basic value dXNlcjpwYXNz",
    "Use HTTP Basic value=dXNlcjpwYXNz",
    "Use HTTP-Basic value dXNlcjpwYXNz",
    "token=abc123",
    '{"token":"abc123"}',
    "'access_token'=abc123",
    "token.value=abc123",
    "token[value]=abc123",
    "Use --token abc123",
    "access token abc123",
    "token abc123",
    "token 123",
    "token abc",
    "token ABCDEF",
    '"token" "abc123"',
    "model token abc123",
    'input token "abc123"',
    'token "abcdef"',
    '"token" "ABCDEF"',
    'token "abc"',
    "input token '123'",
    "token.value abc123",
    "token[value] abc123",
    "request.token abc123",
    "request/token abc123",
    "request-token abc123",
    "requesttoken abc123",
    "report input\u001ctoken: 123456",
    "token used: 'abc'",
    "Use abc123 as model [token]",
    "Count requests. Use model token 123",
    "Finished counting. Model token 123",
    'Finished "counting." Model token 123',
    "Count model tokens 123456789012345678901234567890",
    "Read {auth}",
    "Read (header)",
    "Read [REDACTED_AUTH_HEADER]",
    "execution at tool.default.svc.cluster.local",
)
