#!/usr/bin/env bash
set -euo pipefail
: "${AZURE_SEARCH_ENDPOINT:?set AZURE_SEARCH_ENDPOINT}"
: "${AZURE_SEARCH_INDEX_NAME:?set AZURE_SEARCH_INDEX_NAME}"
cat > "$(dirname "$0")/output.env" <<OUT
SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
SEARCH_INDEX=${AZURE_SEARCH_INDEX_NAME}
AZURE_SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
AZURE_SEARCH_INDEX_NAME=${AZURE_SEARCH_INDEX_NAME}
OUT
printf 'wrote %s\n' "$(dirname "$0")/output.env"
